import json
from sqlalchemy.orm import Session
from fastapi import HTTPException
from datetime import datetime

from app.models.dns_record import DnsRecord
from app.models.hosted_zone import HostedZone


class ImportExportService:
    def __init__(self, db: Session):
        self.db = db

    def export_json(self, zone_id: str, owner_id: int) -> dict:
        zone = self.db.query(HostedZone).filter_by(id=zone_id, owner_id=owner_id).first()
        if not zone:
            raise HTTPException(status_code=404, detail="Hosted zone not found")
        records = self.db.query(DnsRecord).filter_by(hosted_zone_id=zone_id).all()
        return {
            "zone": {
                "id": zone.id,
                "domain_name": zone.domain_name,
                "type": zone.type,
                "comment": zone.comment,
                "created_at": zone.created_at.isoformat(),
            },
            "records": [
                {
                    "id": r.id,
                    "name": r.name,
                    "type": r.type,
                    "ttl": r.ttl,
                    "values": json.loads(r.values),
                    "routing_policy": r.routing_policy,
                    "is_system": r.is_system,
                }
                for r in records
            ],
        }

    def export_bind(self, zone_id: str, owner_id: int) -> str:
        zone = self.db.query(HostedZone).filter_by(id=zone_id, owner_id=owner_id).first()
        if not zone:
            raise HTTPException(status_code=404, detail="Hosted zone not found")
        records = self.db.query(DnsRecord).filter_by(hosted_zone_id=zone_id).all()

        lines = [
            f"; Zone file for {zone.domain_name}",
            f"; Generated by Route53 Clone on {datetime.utcnow().isoformat()}Z",
            f"$ORIGIN {zone.domain_name}",
            f"$TTL 300",
            "",
        ]
        for r in records:
            values = json.loads(r.values)
            for val in values:
                if isinstance(val, dict):
                    # MX, SRV, CAA etc
                    val_str = " ".join(str(v) for v in val.values())
                else:
                    val_str = str(val)
                lines.append(f"{r.name}\t{r.ttl}\tIN\t{r.type}\t{val_str}")

        return "\n".join(lines)
